# waste_analysis.py
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set visual theme
sns.set_theme(style="whitegrid")

# ==========================================
# 1. LOAD AND INSPECT THE DATA
# ==========================================
csv_file = "household_waste_data.csv"
df = pd.read_csv(csv_file)

print("--- Initial Inspection (.head()) ---")
print(df.head())

print("\n--- Structural Overview (.info()) ---")
df.info()

# ==========================================
# 2. DATA CLEANING & FEATURE ENGINEERING
# ==========================================
print("\n--- Cleaning Missing Values ---")
# Count missing values before cleaning
print(df.isnull().sum())

# Handle missing data (Fill NaNs with the average of that column)
df["Organic_Waste_kg"] = df["Organic_Waste_kg"].fillna(df["Organic_Waste_kg"].mean())

# Combine specific waste categories to create a total column
df["Total_Waste_kg"] = df["Organic_Waste_kg"] + df["Plastic_Waste_kg"] + df["Paper_Waste_kg"]

# Convert date string to datetime object and extract day profiles
df["Date"] = pd.to_datetime(df["Date"])
df["Day_of_Week"] = df["Date"].dt.day_name()

print("\nData cleaning and feature engineering finalized.")

# ==========================================
# 3. STATISTICAL SUMMARIES (EDA)
# ==========================================
print("\n--- Key Aggregations & Insights ---")

# Sort zones based on total waste volume for proper order
zone_summary = df.groupby("Zone")["Total_Waste_kg"].sum().round(2).reset_index()
zone_summary = zone_summary.sort_values(by="Total_Waste_kg", ascending=False)
print("\nTotal Waste Generated by Zone:")
print(zone_summary)

# Overall category totals
total_organic = df["Organic_Waste_kg"].sum()
total_plastic = df["Plastic_Waste_kg"].sum()
total_paper = df["Paper_Waste_kg"].sum()

# ==========================================
# 4. BUILDING THE VISUALIZATION DASHBOARD
# ==========================================
fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle("Household Waste Management Analytics Dashboard", fontsize=20, fontweight="bold", y=0.95)

# Chart 1: Waste Composition Breakdown (Pie Chart)
waste_types = ["Organic", "Plastic", "Paper"]
waste_totals = [total_organic, total_plastic, total_paper]
axes[0, 0].pie(waste_totals, labels=waste_types, autopct="%1.1f%%", colors=["#4CAF50", "#FF9800", "#2196F3"], startangle=140)
axes[0, 0].set_title("Overall Waste Composition Breakdown", fontsize=14)

# Chart 2: Total Waste Generation by Zone (Sorted Bar Chart)
sns.barplot(ax=axes[0, 1], data=zone_summary, x="Zone", y="Total_Waste_kg", hue="Zone", order=zone_summary["Zone"])
axes[0, 1].set_title("Total Waste Generated Across Different Zones", fontsize=14)
axes[0, 1].set_xlabel("Zone")
axes[0, 1].set_ylabel("Total Waste (kg)")

# Chart 3: Waste Profile by Household Size (Box Plot)
sns.boxplot(ax=axes[1, 0], data=df, x="Household_Size", y="Total_Waste_kg", hue="Zone")
axes[1, 0].set_title("Waste Distribution by Household Size", fontsize=14)
axes[1, 0].set_xlabel("Household Size")
axes[1, 0].set_ylabel("Total Waste per Day (kg)")

# Chart 4: Weekly Waste Production Schedule (Ordered Timeline Bar Chart)
day_order = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
day_summary = df.groupby("Day_of_Week")["Total_Waste_kg"].mean().reindex(day_order).reset_index()

sns.barplot(ax=axes[1, 1], data=day_summary, x="Day_of_Week", y="Total_Waste_kg", hue="Day_of_Week", order=day_order, palette="crest")
axes[1, 1].set_title("Average Waste Generation by Day of the Week", fontsize=14)
axes[1, 1].set_xlabel("Day of the Week")
axes[1, 1].set_ylabel("Avg Waste Generated (kg)")
axes[1, 1].tick_params(axis="x", rotation=45)

# Tight layout tuning to avoid overlaps
plt.tight_layout(rect=[0, 0, 1, 0.92])

# Save dashboard as high-resolution image
plt.savefig("waste_analysis_dashboard.png", dpi=300)
print("\nSuccess! 'waste_analysis_dashboard.png' has been saved to your workspace.")